
# Global site settings
title: Joint workshop -- COLT and IMS 2022
subtitle: 
permalink: "/:categories/:title.html"
baseurl: "/colt-ims-2022.github.io"
url: ""


# Also generate pages with dates in the future
future: true


# Additional build settings
markdown: kramdown


# Minify HTML
compress_html:
  clippings: all
  comments: all
  blanklines: true


# Include image banner file name below
banner: banner.jpg


# Conference information
conference:

  draft: false
  hide_tentative: true

  name: Joint workshop -- COLT and IMS 2022
  shortname: COLT-IMS
  venue: London
  venue_url:  
  location: London, United Kingdom
  year: 2022
  month: July
  dates:
  - 2022-07-01
  # - 2020-10-26
  # - 2020-10-27
  # - 2020-10-28

  support:
  - name: COLT
    url: ""
  - name: IMS
    url: 

  general:
  - given: Benjamin
    family: Guedj
    url: "http://inverseprobability.com"
    institute: University of Cambridge
  - given: Peter
    family: Grünwald
    url: "https://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon
  - given: Susan
    family: Murphy
    url: "https://ei.is.tuebingen.mpg.de/person/bs"
    institute: MPI for Intelligent Systems (Tübingen) and Amazon  

  # local:
  # - given: Gergely
  #   family: Neu
  #   url: http://cs.bme.hu/~gergo/
  #   institute: Universitat Pompeu Fabra
  # - given: Vicenç 
  #   family: Gómez
  #   url: https://www.upf.edu/web/vgomez
  #   institute: Universitat Pompeu Fabra

  # workshop:
  # - given: Gergely
  #   family: Neu
  #   url: http://cs.bme.hu/~gergo/
  #   institute: Universitat Pompeu Fabra
  # - given: Lorenzo 
  #   family: Rosasco
  #   url: http://web.mit.edu/lrosasco/www/
  #   institute: Universita' di Genova and Massachusetts Institute of Technology

  # assistants:
  # - given: Diana
  #   family: Rebmann
  #   institute: DeepMind (Montréal)
  # - given: Timothy
  #   family: Gebhard
  #   url: "https://timothygebhard.de"
  #   institute: MPI for Intelligent Systems (Tübingen) and ETH Zurich

  # steering:
  # - given: Zoubin
  #   family: Ghahramani
  #   url: "http://mlg.eng.cam.ac.uk/zoubin/"
  #   institute: University of Cambridge and Uber
  # - given: Thomas
  #   family: Hofmann
  #   url: "http://www.da.inf.ethz.ch/people/ThomasHofmann/"
  #   institute: ETH Zurich
  # - given: Neil D.
  #   family: Lawrence
  #   url: "http://inverseprobability.com"
  #   institute: University of Cambridge
  # - given: Bernhard
  #   family: Schölkopf
  #   url: "https://ei.is.tuebingen.mpg.de/person/bs"
  #   institute: MPI for Intelligent Systems (Tübingen) and Amazon


# Set up collections (for workshops and schedule)
collections:
  workshops:
    output: false
    permalink: /workshops/:name
  schedule:
    output: true
    permalink: /schedule/:name

# Social media settings
contact_email: benjamin.guedj@inria.fr
github_username: bguedj
twitter_username: bguedj
